services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    image: banana-backend:${TAG:-latest}
    platform: ${PLATFORM:-linux/amd64}    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    image: banana-frontend:${TAG:-latest}
    platform: ${PLATFORM:-linux/amd64}
