# 专门用于运行服务（开发环境）
version: '3.8'
services:
  backend:
    image: banana-backend:latest
    container_name: banana-backend
    env_file:
      - ./backend/.env
    environment:
      # 服务器配置
      - PORT=3001
      - NODE_ENV=production
      
      # JWT 配置
      - JWT_SECRET=iwillQiaoberigAnhtheMierewaitMieingforyou
      - JWT_EXPIRES_IN=7d
      
      # MySQL 数据库配置（Docker 环境）
      - DB_HOST=mysql  # 使用服务名
      - DB_PORT=3306
      - DB_NAME=banana_chat
      - DB_USER=banana_user
      - DB_PASSWORD=banana_pass
      
      # Google Gemini API
      - GEMINI_API_KEY=your-gemini-api-key
      
      # 微信支付配置
      - WECHAT_PAY_APP_ID=wx5c828a9210a01945
      - WECHAT_PAY_API_KEY=xh5ikQIAOebdANixewdMIEwaMIE9kuzc
      - WECHAT_PAY_MCH_ID=1726726778
      - WECHAT_PAY_NOTIFY_URL=http://localhost:3001/api/payment/notify
      
      # 微信登录配置
      - WECHAT_AUTH_APP_ID=${WECHAT_AUTH_APP_ID}
      - WECHAT_AUTH_APP_SECRET=${WECHAT_AUTH_APP_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - banana-network

  frontend:
    image: banana-frontend:latest
    container_name: banana-frontend
    environment:
      - DISABLE_ESLINT_PLUGIN=true
      - REACT_APP_WECHAT_AUTHAPP_ID=${WECHAT_AUTH_APP_ID}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  banana-network:
    driver: bridge